Yevhen-Hrafov_
yurii-polishchuk/gl-java-mentorship-july-2022 pull request #19
Opened 2022-07-14 14:37 UTC by hrafov

2022-07-21 09:24 UTC, AntonTsa commented
1) Names of columns in Entity Host don't match ones in sql script
2) Repository is not initialized in Service
3) Incorrect Controller's logic. Implemented POST method instead of GET

2022-07-21 13:26 UTC, yurii-polishchuk requested changes

2022-07-21 13:26 UTC, yurii-polishchuk commented on META-INF/MANIFEST.MF
> +Main-Class: com.example.statussvc.Application
Please remove this file

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> -
please leave this new line as was before.

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> +    public Host retrieve(@PathVariable Long id) {
Please refactor.

1. use custom RetrieveHostResponse and create it in a wire package.
2. use wrapper ResponseEntity

`public ResponseEntity<RetrieveHostResponse> retrieve(@PathVariable Long id) { ... }`

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> +        return HostsRepository.getHost(id);
do not call Repository in Controller. Please read Spring MVC + Patterns:

- https://www.baeldung.com/spring-mvc
- https://tom-collings.medium.com/controller-service-repository-16e29a4684e5

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/Host.java
> +    private String title;
please remove. should be created by @AntonTsa

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +@ExtendWith(SpringExtension.class)
new line after import

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +@WebMvcTest(controllers = RootController.class)
why are you testing Root Controller?

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +    private final MockMvc mockMvc;
new line after {

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +    @BeforeEach
new line after tracer;

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +            GIVEN valid root endpoint
please revisit Display Name and read about it. https://mkyong.com/junit5/junit-5-display-names/

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +        assertThat(!actualResponse.getContentAsString().isEmpty());
do not use ! in asserts. Please read the documentation and check how to assert.

plus, why are you testing `/hosts` ? your endpoint is `/hosts/{id}`

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +        MockHttpServletResponse actualResponse = mockMvc.perform(get("/abc")
what exactly are you testing here? we don't have `/abc` endpoint

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +        assertThat(actualResponse.getContentAsString().isEmpty());
what your test is testing?

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> +    public ResponseEntity<URL> retrieve(@PathVariable("id") Long id) throws URISyntaxException {
Please read: https://www.restapitutorial.com/lessons/httpmethods.html and update properly Controller based on REST Specification.

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/Host.java
> +@Table(name = "URLS")
why URLS? table should be named hosts as per mapping

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +        HostsRepository repository;
use @Autowired to inject repository

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> +Create table urls (
please remove - this is not a part of your PR

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +    void ValidHostsEndpoint() throws Exception {
please remove this test, and read carefully your task.

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +                .andExpect((ResultMatcher) jsonPath("$.id").value("1"));
please use ObjectMapper to get data from the response and compare via assert with your prepared expected results

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +        MockHttpServletResponse actualResponse = mockMvc.perform(get("/bad_hosts")
what exactly are you testing here? that there is no endpoint mapped? this test is not helping to test your /hosts/{id} endpoint at all

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +        assertThat(actualResponse.getStatus() == 404);
please read how to properly use asserts in ANY kind of testing.

- https://www.baeldung.com/introduction-to-assertj
- https://www.tutorialspoint.com/junit/junit_using_assertion.htm
- https://www.guru99.com/junit-assert.html
- https://www.vogella.com/tutorials/AssertJ/article.html

2022-07-21 13:26 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +        MockHttpServletResponse actualResponse = mockMvc.perform(get("/hosts?")
again, your not testing your functionality, just some random endpoints - that are not bringing any value by a test

2022-07-25 09:02 UTC, yurii-polishchuk requested changes

2022-07-25 09:02 UTC, yurii-polishchuk commented on META-INF/MANIFEST.MF
> +Main-Class: com.example.statussvc.Application
still a valid comment, please remove.

2022-07-25 09:02 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> +        return RetrieveHostResponse.findById(id);
you need to call Service layer to e.g. `hostService.retrieve(id)`

2022-07-25 09:02 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/type/Host.java
> +public class Host {
please remove this class, we already have Host.java object

2022-07-25 09:02 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +    @Autowired
annotation is not needed here. just:
```
private final HostsRepository hostsRepository;
```

2022-07-25 09:02 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +        return hostsRepository.findById(id).orElseThrow();
orElseThrow() what? I'd recommend throwing 404 e.g. ```HttpClientErrorException.NotFound```

2022-07-25 09:02 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/response/RetrieveHostResponse.java
> +public class RetrieveHostResponse implements Response {
please add fields to response + I would suggest to use `record` from Java16+

2022-07-25 09:02 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> +Create table urls (
still valid comment, please remove

2022-07-25 09:02 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +    @DisplayName("get endpoint with existing id")
please use GIVEN / WHEN / THEN

2022-07-26 10:22 UTC, yurii-polishchuk requested changes

2022-07-26 10:22 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +        } catch (HttpClientErrorNotFoundException e) {
why are you throwing and then immediately catching an exception? o_O

2022-07-26 10:22 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/response/RetrieveHostResponse.java
> +public record RetrieveHostResponse(@JsonProperty String title,
can we avoid @JsonProperty ?

2022-07-26 10:22 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostControllerTest.java
> +    @DisplayName("get endpoint with existing id - expected 200 OK")
please check format of the test and display name naming convention

```
"""
GIVEN ...
WHEN ...
THEN ...
"""
```

2022-07-28 10:07 UTC, yurii-polishchuk requested changes

2022-07-28 10:07 UTC, yurii-polishchuk commented on META-INF/MANIFEST.MF
> +Main-Class: com.example.statussvc.Application
still valid, please remove

2022-07-28 10:07 UTC, yurii-polishchuk commented on gitignore
> +MANIFEST.MF
we already have gitignore file, please reuse

2022-07-28 10:07 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/type/Host.java
> +public class Host {
please pull latest changes

2022-07-28 10:07 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/response/RetrieveHostResponse.java
> +public class RetrieveHostResponse implements Response {
any updates here?

2022-07-28 10:07 UTC, yurii-polishchuk commented on src/main/resources/application.yml
> +    driverClassName: com.mysql.jdbc.Driver
pool latest changes from main

2022-07-28 10:07 UTC, yurii-polishchuk commented on src/test/resources/application-test.yml
> +    driverClassName: com.mysql.jdbc.Driver
pull latest changes, this was fixed.

2022-07-29 18:51 UTC, yurii-polishchuk approved these changes

2022-07-29 18:51 UTC, yurii-polishchuk submitted a review, later dismissed

2022-07-29 19:02 UTC, closed without merging