Created Migration
yurii-polishchuk/gl-java-mentorship-july-2022 pull request #20
Opened 2022-07-19 16:36 UTC by AntonTsa

Created Post Controller, Service, Repo
Tested Controller

2022-07-20 08:56 UTC, hrafov reviewed
In class HostControllerTest.java in string #78 will be reasonable use constants from class Constants.java - "API_V1 + URL_SERARATOR + HOSTS"

2022-07-20 09:44 UTC, hrafov reviewed
The name of the class is HostCreate, it is a verb not a noun.

2022-07-21 13:19 UTC, yurii-polishchuk requested changes

2022-07-21 13:19 UTC, yurii-polishchuk commented on build.gradle
> +    manifest {
why do you need this one? we'r not using jar, but rather fatjar from springboot

2022-07-21 13:19 UTC, yurii-polishchuk commented on build.gradle
> +    //enabled = false
?

2022-07-21 13:19 UTC, yurii-polishchuk commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
please revert back, that's auto-generated by gradle and escape symb should be present

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/Constants.java
> +    public static final String HOSTS = "hosts";
no need to keep it in constants file,just move to HostsController as it will be only used there.

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/handler/GlobalExceptionHandler.java
> -    @SuppressWarnings("unused")
please keep this annotation

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/handler/GlobalExceptionHandler.java
> +
do we need these 2 lines ? :)

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/application-dev.yml
> +    password: Password_23
please revert password change. I bet you could change password in docker container

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/application-dev.yml
> +    showSql: false
it's good to show SQL in dev mode for debug purpose

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/application.yml
> +      ddlAuto: validate # update to validate
if it was changed, please remove comment

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/resources/application-test.yml
> +    url: jdbc:mysql://localhost:3306/${spring.application.name}db
please revert back, tests are using totally different data and not your local

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> +    public ResponseEntity<URI> create(@Valid @RequestBody HostCreate hostCreate) throws Exception {
you don't need to return from POST, your already setting header with URL for resource + name for HostCreate should be different + use https://projectlombok.org/features/SneakyThrows for URL thow exception. Please see example:

```
@PostMapping
@SneakyThrows
public ResponseEntity<Void> create(@RequestBody @Valid CreateHostRequest createHostRequest) {
 ...
}
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> +        return ResponseEntity.created(uri).build();
you could inline everything, and this will eliminate throws Exception or SneakyTHrow.

```
 ....
        return ResponseEntity.created(
                        URI.create(API_V1 + URL_SEPARATOR + HOSTS + URL_SEPARATOR + hostsService.save(hostCreate)))
                .build();
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/Host.java
> +    private Date lastCheck;
I would rather use:

```
@NotNull
private LocalDateTime lastCheck;
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/Host.java
> +    @Min(1)
why min 1 and not 0 for example?

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/mapper/HostMapper.java
> +public interface HostMapper {
let's slightly change it from interface to abstract class to leverage dependency injection:

```
public abstract class HostMapper {
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/mapper/HostMapper.java
> +    HostMapper INSTANCE = Mappers.getMapper(HostMapper.class);
please remove this instance, we will inject it with Spring Dependency Injection to Service

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/mapper/HostMapper.java
> +    Host HostCreateRequestToHost(HostCreate hostCreate);
add public abstract and then just name as toHost e.g.

```
public abstract Host toHost(CreateHostRequest createHostRequest);
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/mapper/HostMapper.java
> +            expression = "java( new java.util.Date() )"
let's remove it for now, we will have different BIZ logic for lastCheck DateTime

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/repository/HostsRepository.java
> -
?

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +    public Long save(@Valid HostCreate hostCreate) {
you don't need @Valid here + rename back to create(...)

```
public Long create(CreateHostRequest createHostRequest) {
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +    private final HostsRepository hostsRepository;
2 dependency injections should be present here:

```
private final HostsRepository hostsRepository;
private final HostMapper hostMapper;
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +        return hostsRepository.save(mappedHost).getId();
just:
```
return hostsRepository.save(hostMapper.toHost(createHostRequest)).getId();
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreate.java
> +    @Pattern(
Create should not allow status to be added (that's internal service logic e.g. PING that would be sent in parallel ad update if active or inactive). Please remove status from Request

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreate.java
> +    private Date lastCheck;
LocalDateTime

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreate.java
> +    @Pattern(
there is @URL validator alrteady from the box. e.g.

```
import org.hibernate.validator.constraints.URL;


@URL
private URL URL;
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreate.java
> +    @Min(value = 0, message = "Connection time < 0ms")
Create should not allow creationTimeout to be added (that's internal service logic e.g. PING that would be sent in parallel). Please remove from Request

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreate.java
> +    private Long id;
why do you need ID on a creation request? that's what DB will return. please remove

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreate.java
> +    @NotBlank(message = "Empty title")
let's remove message for now

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreate.java
> +@AllArgsConstructor
please remove all these annotations and use `record` from Java 16+

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> +    status varchar(100) not null,
I bet varchar(32) is enough

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> +    last_check datetime(6) not null,
I would rather use `timestamp`

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> +    url varchar(300) not null,
URL could be pretty long, let's have at least varchar(1024)

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> + create table if not exists host (
remove if not exists, this will be ahdnled by FlyWay

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> +) engine=InnoDB;
tou could also add

```
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_general_ci;
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +    private final HostsService hostsService;
if you are Mocking service, yo udon't need to autowire it...

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +@MockBean(Tracer.class)
you could combine @MockBean e.g.

```
@MockBean(
        classes = {
                HostsService.class,
                Tracer.class
        },
        answer = Answers.RETURNS_SMART_NULLS
)
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +    private final ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
just Auwowire ObjectMapper if you need it, but let's first discuss if you need it.

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +        given(hostsService.save(any())).willReturn(100L);
never use any, always valudate specific object e.g. 

```
given(hostsService.save(hostCreate)).willReturn(100L);
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +                        .content(ow.writeValueAsString(hostCreate))
Autowire object mapper and then

```
objectMapper.writeValueAsString(hostCreate)
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +        assertThat(actualResponse.getHeader("location")).isEqualTo("/api/v1/hosts/100");
assert that there is no body as well.

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +        assertThat(actualResponse.containsHeader("location")).isTrue();
```
assertThat(actualResponse.getHeader(HttpHeaders.LOCATION))
                .isNotEmpty()
                .isEqualTo(EXPECTED_RESPONSE_URL);
```

2022-07-21 13:19 UTC, yurii-polishchuk commented on build.gradle
>      implementation "org.flywaydb:flyway-core"
can we remove core? or we need both?

2022-07-21 13:19 UTC, yurii-polishchuk commented on build.gradle
> -    enabled = false
please add boot fat jar instead.

```
bootJar {
    archiveBaseName.set rootProject.name
    archiveVersion.set ""
    mainClass.set "com.example.statussvc.Application"
}
```
- https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/
-  https://docs.spring.io/spring-boot/docs/2.7.1/gradle-plugin/api/org/springframework/boot/gradle/tasks/bundling/BootJar.html

2022-07-21 13:19 UTC, yurii-polishchuk commented on build.gradle
> +    //useJUnitPlatform()
why?

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/HostsController.java
> +    public ResponseEntity<URI> create(@Valid @RequestBody HostCreateDto hostCreateDto) throws Exception {
please do not name objects as DTO, tha'ts a legacy name of naming. if that's a request - name it as a request. `CreateHostRequest createHostRequest`

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/handler/exceptions/ConflictException.java
> +public class ConflictException extends RuntimeException{
needless, you don't need a custom excaption, Spring has already some out of the box. Let's TBD on a meeting. We could use WebClientResponseException.Conflict.class

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/handler/GlobalExceptionHandler.java
> +        return map(EXCEPTION_MAPPING.getOrDefault(exception.getClass(), HttpStatus.NOT_FOUND),
nope, that should be BAD_REQUEST. + you don't need to use EXCEPTION_MAPPING, just handle this specific exception

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/mapper/HostMapper.java
> +    HostCreateDto hostToHostCreateResponse(Host host);
`CreateHostRequest` instead of HostCreateDto

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +        if (mappedHost.getId() != null && hostsRepository.existsById(mappedHost.getId())) {
same, you don't need use `exist` before `save`. The database will handle that. Plus how exactly will you receive conflict if DB is generating ID ? You could not pass ID in the POST - that's not in REST spec.

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/wire/request/HostCreateDto.java
> +public class HostCreateDto implements Request {
CreateHostRequest + make it record

2022-07-21 13:19 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +            THEN return response with code 404 and message "Not Found"
by REST specification it should be 401. Please read carefully: https://www.restapitutorial.com/httpstatuscodes.html

2022-07-21 13:24 UTC, yurii-polishchuk requested changes

2022-07-21 13:24 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +    private final ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
private final ObjectMapper objectMapper;

2022-07-22 10:45 UTC, yurii-polishchuk requested changes

2022-07-22 10:45 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/Host.java
> +    private Integer connectionTime;
can we use Duration ? seems more appropriate

2022-07-22 10:45 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +        mappedHost.setConnectionTime(0);
this is a logif of Mapper, please use methods inside Mapper class and not here.

```
      mappedHost.setConnectionTime(0);
         mappedHost.setLastCheck(new Date());
         mappedHost.setStatus(Status.INACTIVE);
```

2022-07-25 09:05 UTC, yurii-polishchuk requested changes

2022-07-25 09:05 UTC, yurii-polishchuk commented on build.gradle
> -    enabled = false
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/controller/handler/GlobalExceptionHandler.java
> -    @SuppressWarnings("unused")
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/domain/Host.java
> +    private Integer connectionTime;
so was it changed or we are keeping Integer?

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/repository/HostsRepository.java
> -
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/HostsService.java
> +        mappedHost.setConnectionTime(0);
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/main/resources/application-dev.yml
> +    password: Password_23
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/main/resources/application.yml
> +      ddlAuto: validate # update to validate
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/main/resources/db.migration.mysql/V1__init.sql
> + create table if not exists host (
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +@MockBean(Tracer.class)
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +    private final HostsService hostsService;
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/test/resources/application-test.yml
> +    url: jdbc:mysql://localhost:3306/${spring.application.name}db
still valid, please update.

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +        assertThat(actualResponse.getHeader("location")).isEqualTo("/api/v1/hosts/100");
don't see any changes?

2022-07-25 09:05 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/controller/HostsControllerTest.java
> +        assertThat(actualResponse.containsHeader("location")).isTrue();
were these changed?

2022-07-27 10:54 UTC, yurii-polishchuk approved these changes

2022-07-27 10:56 UTC, merged