[CRON] implement basic scheduler job for running task #14
yurii-polishchuk/gl-java-mentorship-july-2022 pull request #23
Opened 2022-07-30 14:29 UTC by AntonTsa

2022-07-31 07:23 UTC, hrafov reviewed
maybe we need to delete all comments like //@Scheduled(cron = "${scheduled.cron}")
and maybe we need to use a properties file to externalize the configuration.

2022-08-01 06:30 UTC, AntonTsa commented
> maybe we need to delete all comments like //@scheduled(cron = "${scheduled.cron}") and maybe we need to use a properties file to externalize the configuration.

I tried to do it using properties, but when I test it, I got:
![image](https://user-images.githubusercontent.com/58445366/182085988-b00bf45f-f6ee-4b19-8031-49ab673f1189.png)

2022-08-01 13:06 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/service/MonitorServiceTest.java
> +                .atMost(Duration.ofMinutes(10L))
not a good idea to have test that just waits 10min

2022-08-01 13:13 UTC, yurii-polishchuk requested changes

2022-08-01 13:13 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/MonitorService.java
> +    @Scheduled(cron = "0 */5 * * * *")
just  
```
@Scheduled(cron = "${application.scheduler.host.availability.cron}")
```

2022-08-01 13:13 UTC, yurii-polishchuk commented on src/main/resources/application.yml
> +#Scheduling
please move under applciation e.g.

`application.scheduler.host.availability.cron: "0 */5 * * * *"

2022-08-01 13:13 UTC, yurii-polishchuk commented on src/main/java/com/example/statussvc/service/MonitorService.java
> +@ConditionalOnProperty(name = "scheduler.enabled", matchIfMissing = true)
why do we need conditions?

2022-08-02 13:17 UTC, yurii-polishchuk requested changes

2022-08-02 13:17 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/service/MonitorServiceTest.java
> +public class MonitorServiceTest {
@EnableConfigurationProperties(ApplicationProperties.class)
 - https://www.baeldung.com/spring-enable-config-properties

2022-08-02 13:21 UTC, yurii-polishchuk requested changes

2022-08-02 13:21 UTC, yurii-polishchuk commented on src/test/java/com/example/statussvc/service/MonitorServiceTest.java
> +public class MonitorServiceTest {
@TestPropertySource(properties = "application.scheduler.host.availability.cron: 0 */5 * * * *")
 - https://www.baeldung.com/spring-test-property-source

2022-08-04 09:46 UTC, closed without merging